package pojo;
// Generated 13-feb-2016 13:43:44 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer id;
     private String calle;
     private String poblacion;
     private String provincia;
     private String codigoPostal;
     private Persona persona;

    public Direccion() {
    }

	
    public Direccion(String calle, String poblacion, String provincia, String codigoPostal) {
        this.calle = calle;
        this.poblacion = poblacion;
        this.provincia = provincia;
        this.codigoPostal = codigoPostal;
    }
    public Direccion(String calle, String poblacion, String provincia, String codigoPostal, Persona persona) {
       this.calle = calle;
       this.poblacion = poblacion;
       this.provincia = provincia;
       this.codigoPostal = codigoPostal;
       this.persona = persona;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @Override
    public String toString() {
        return "Direccion:\nID: "+this.id+"\nCalle: "+this.calle+"\nPoblación: "+this.poblacion+"\nProvincia: "+this.provincia+"\nCodigo Postal: "+this.codigoPostal+"\n";
    }




}


